name: PR units
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.3.4

      - name: setup-go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3.2.0
        with:
          go-version: "1.18"

      - name: detect-workflow tests
        run: |
          set -euo pipefail

          cd .github/actions/detect-workflow

          # Download dependencies.
          go mod vendor

          # Test.
          go test -mod=vendor -v ./...

      - name: Generic API tests
        run: |
          set -euo pipefail

          # Download dependencies.
          go mod vendor

          # Test.
          go test -mod=vendor -v ./...

      - name: Go builder tests
        run: |
          set -euo pipefail

          # Go tests.
          cd internal/builders/go/

          # Download dependencies.
          go mod vendor

          # Build.
          go build -mod=vendor

          # Tests.
          go test -mod=vendor -v ./...
