name: PR units
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4

      - name: setup-go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.18"

      - name: detect-workflow tests
        run: |
          set -euo pipefail

          cd .github/actions/detect-workflow

          # Download dependencies.
          go mod vendor

          # Test.
          go test -mod=vendor -v ./...

      - name: Generic API tests
        run: |
          set -euo pipefail

          # Download dependencies.
          go mod vendor

          # Test.
          go test -mod=vendor -v ./...

      - name: Go builder tests
        run: |
          set -euo pipefail

          # Go tests.
          cd internal/builders/go/

          # Download dependencies.
          go mod vendor

          # Build.
          go build -mod=vendor

          # Tests.
          go test -mod=vendor -v ./...
